// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPZC2lSQCk2lf4HthI3VW6ldzBlaw6e2k',
    appId: '1:605202542090:web:3e5fa997c8c7d9c2d7f9f3',
    messagingSenderId: '605202542090',
    projectId: 'wefit-d6233',
    authDomain: 'wefit-d6233.firebaseapp.com',
    storageBucket: 'wefit-d6233.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl9OuWrKBHEYyELTto5eFPniB3eGT5eK0',
    appId: '1:605202542090:android:08e7739de53d41d6d7f9f3',
    messagingSenderId: '605202542090',
    projectId: 'wefit-d6233',
    storageBucket: 'wefit-d6233.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU93tikuXwiawnokPE6RaVyFAscIlwyEc',
    appId: '1:605202542090:ios:aadda63346ecb08bd7f9f3',
    messagingSenderId: '605202542090',
    projectId: 'wefit-d6233',
    storageBucket: 'wefit-d6233.appspot.com',
    iosBundleId: 'com.example.itec303',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU93tikuXwiawnokPE6RaVyFAscIlwyEc',
    appId: '1:605202542090:ios:aadda63346ecb08bd7f9f3',
    messagingSenderId: '605202542090',
    projectId: 'wefit-d6233',
    storageBucket: 'wefit-d6233.appspot.com',
    iosBundleId: 'com.example.itec303',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPZC2lSQCk2lf4HthI3VW6ldzBlaw6e2k',
    appId: '1:605202542090:web:340326c53bf32b1fd7f9f3',
    messagingSenderId: '605202542090',
    projectId: 'wefit-d6233',
    authDomain: 'wefit-d6233.firebaseapp.com',
    storageBucket: 'wefit-d6233.appspot.com',
  );
}
